---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-basic-auth
  namespace: openclaw
spec:
  encryptedData:
    auth: AgCFISnpqZRDC0ngXD53mkoEPz6hmAJBTL+Rrgxu5msCLPfOrYRM6OUo5e+Tpt7PGF7pjI5dCpgzF5CZKdpfshmftohtmTMIEtjOv0q9ZhY59DkM2yAf59XTtc3s5STFy55mx14TzxWK0x1StdHHSWF9hKHwrKPOjtpVk0MBJNfKYMC8NZE0J8FeoNPFYJSnJ97G2NOowjEu+ibLv2tLEUOWTMtdE/6m+eAGqJScpJPJnIOL16onJhwum2MksrKeD95Pcf+6tIRcjR0+zpPm4tO3md8p4nGFiU0afSKNnen/fpUWSdjDeJXujFMeNytH0JzfnPQhvxl0oDCBIGz8mQ8tl2mUbqbGrDotF6AuNQPjBGD8rMqL0ZIDBfL+Wt0nQV+MOVzNLqFvtVhQwqnRXjEBxFq69JGFWH0CrQ0wlIIIliEcnUwjFmvEbHvMviQ6kZawdF8ItfzwPcuX/9AZl1hrctJBg8X20qSAvgXSEJ6l4aG8DALwpNeSZuRuWxkfZvkC4+28Suio7YcyHvb14NmKIQAG5ShXT8VaGeV4uB6U4Lm11TeFsKhaOoAkMIgWVbwlvaEKp4CV3SGZhWOrFZpLonyqZaSstoEQ07jlYDWIXEa+iY37+rhaJP0h1jVY61UVFpSMvUgH+ZZTyn4EQPNvYaZtjCWIXrtloHBriFTjfxr/Epk4Ja+eXrnE6eiN2+IKb/MaNCSUOuzuczPPM8czFUHVViO+kC3YR+4LJD+2YTOPyFibZ7QOAJPiaLY4aMc85A==
  template:
    metadata:
      name: openclaw-basic-auth
      namespace: openclaw
