---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secret
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgCbdKKRalPgzPWIFg6OpWMIPx/PaB/pmI2FGlo3gbWRMeT7MHwJjN5CFwIPG80H47Y662p1/wvrlIhdMJc0XGszZhdxA5LyIkKyuvJKCDfHAmOeDtKziKsuLWWBlxVn7HY1M7bkwxuUt0YHScK8CpxPH/FOcdxU+Sd0zfEHMtEydLatgQx+nvHSG1qFA32dIwhK16a55i3E7SuEdCWsrs/lqXlKuh8JpIZAGD+Q2OwPlUYXFQUF5f9CdK2DD9zwBnSaDas7T3k7iWVVIhLM1MWxToK/6QQkvGm5RJ6MOxLkVR4b/a4C3vwjTKoQv3N7uEnglyAUCXf5KappPhf7IJcmkmYPFMMnTcyhKvlVtAPYdxBYFVuT1EtbzVriTWgmQT2BhXkxRISs/elHwVYzsblKbZsF/kAj/Uso8uovZnbGjvIaoHyB8LTN8rxvVmfZXytya1DnbFcd7khjKuwHrFKOBd5p83rNFbVhmgDStkrBR2cKe2Jkr4W5WTH5PnSbGLkTr3UbCG/dHZ6fnugHVHFKX2aPUnJO6wBI33k3FE7Z+fSl5HqnAdmq9seenIsp/2UNZaFOY92J60DyYc+8Aw2mGn58BB9aUp1yI9o+nBhqKkO00+ciXIrID8+/mWOtRQNv6UjwMIlvPd3eOBKI+bhSEC4SFcq0xfJSlZqYffeiMWMwMJfnG9C1Y5i0ZFwI3nlSkNW0I+5Q8uML8b3PwMa0a74yLqGktaic8NDSAFRed4usxrtQoI4oEJio7bkFohenNJK8ctMp2AE9RWqyPPBOiS5qp9bRgQrrnp3xmqa+lmi5Nrw8eEVp3Wg4KWjEibVYRXsXqX55tXlNjjV8pNtmvFuXEhbyyL3cff4d954f3xoJ3os5CvYCGYVsgTw+abcGke0M0MI5+jIMf4X/48xy
  template:
    metadata:
      name: openclaw-secret
      namespace: openclaw
