---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secret
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_PASSWORD: AgA0XC3/wi4lcQcZvOeA4gNx5SsDzxPvnOZstNigid6GP/lU8vmYvEorEgHPMPMwEWot5p4LaRQBp15hMxSoMHWInVHbXPP9RYdIEs04CaZlO4m4eaIgVt+S+VwZaLgzgtWTQr9HhfUBMw+UoJrWFcuf31oC9dAC42kLmx2eIq96Z/FrLUWlp47kbx1G+hgUEklBaUgXCcC+bo8mb5BTHkqX7bARqrBw1roynsDG9lKyS0mtZtgwPger/qHFA4g7sXt16kTcPr3CW30JoETABptG0Jggbzyy2NhHKAbG8ECcXDoL3ATHOxTIFDV4om24WUJzvs/RTzt8Lzbi+7D0vK4qUHCQgXxPhnukjo4Dx6+nqBV00EefLRRlOP5xikCCpWtaay5iOMrmtzhqGNfpfjLBlat4bHm3ZzDEvDuhSpfu1R3YvaOVXYwKPW6Yxvve1Uqq3SAhuQD8a0ANqirQGePCHF83rJ8z3ophegULSoN3kyjWQKzrbQuLxLHSXakrWgcmtyVxUfUquJvmfEHNZmLRJmcBPyLs5Er5kbx0/+tdaNs5iqBmkmPYMsxyWMwXaJi+l5ircAXLk6M7V5e6ZQ1zthz7hUUkoxbJB8DhWGjVAFFUy15gcMZTgJqZf3eZcuDme+bpt5oTsKLmkaEAFEnRXE3Bh+vsEIk9lz99qSPpJNscG5ThNFfeTuvAzQavB17/yZBtugehT58lo6A=
  template:
    metadata:
      name: openclaw-secret
      namespace: openclaw
